// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enginepb.proto

#include "enginepb.pb.h"

#include <algorithm>

#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/wire_format_lite_inl.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace enginepb
{
class CommandRequetHeaderDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<CommandRequetHeader> _instance;
} _CommandRequetHeader_default_instance_;
class CommandRequetDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<CommandRequet> _instance;
} _CommandRequet_default_instance_;
class ResponseHeaderDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<ResponseHeader> _instance;
} _ResponseHeader_default_instance_;
class CommandResponseDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<CommandResponse> _instance;
} _CommandResponse_default_instance_;
class SnapshotDataDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<SnapshotData> _instance;
} _SnapshotData_default_instance_;
class SnapshotRequestDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<SnapshotRequest> _instance;
    const ::metapb::Region *                                             region_;
    const ::enginepb::SnapshotData *                                     data_;
} _SnapshotRequest_default_instance_;
class SnapshotDoneDefaultTypeInternal
{
public:
    ::google::protobuf::internal::ExplicitlyConstructed<SnapshotDone> _instance;
} _SnapshotDone_default_instance_;
} // namespace enginepb
namespace protobuf_enginepb_2eproto
{
void InitDefaultsCommandRequetHeaderImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    {
        void * ptr = &::enginepb::_CommandRequetHeader_default_instance_;
        new (ptr)::enginepb::CommandRequetHeader();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::CommandRequetHeader::InitAsDefaultInstance();
}

void InitDefaultsCommandRequetHeader()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCommandRequetHeaderImpl);
}

void InitDefaultsCommandRequetImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    protobuf_enginepb_2eproto::InitDefaultsCommandRequetHeader();
    protobuf_raft_5fcmdpb_2eproto::InitDefaultsRequest();
    protobuf_raft_5fcmdpb_2eproto::InitDefaultsAdminRequest();
    protobuf_raft_5fcmdpb_2eproto::InitDefaultsAdminResponse();
    {
        void * ptr = &::enginepb::_CommandRequet_default_instance_;
        new (ptr)::enginepb::CommandRequet();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::CommandRequet::InitAsDefaultInstance();
}

void InitDefaultsCommandRequet()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCommandRequetImpl);
}

void InitDefaultsResponseHeaderImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    {
        void * ptr = &::enginepb::_ResponseHeader_default_instance_;
        new (ptr)::enginepb::ResponseHeader();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::ResponseHeader::InitAsDefaultInstance();
}

void InitDefaultsResponseHeader()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsResponseHeaderImpl);
}

void InitDefaultsCommandResponseImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    protobuf_enginepb_2eproto::InitDefaultsResponseHeader();
    protobuf_raft_5fserverpb_2eproto::InitDefaultsRaftApplyState();
    {
        void * ptr = &::enginepb::_CommandResponse_default_instance_;
        new (ptr)::enginepb::CommandResponse();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::CommandResponse::InitAsDefaultInstance();
}

void InitDefaultsCommandResponse()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCommandResponseImpl);
}

void InitDefaultsSnapshotDataImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    protobuf_raft_5fserverpb_2eproto::InitDefaultsKeyValue();
    {
        void * ptr = &::enginepb::_SnapshotData_default_instance_;
        new (ptr)::enginepb::SnapshotData();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::SnapshotData::InitAsDefaultInstance();
}

void InitDefaultsSnapshotData()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSnapshotDataImpl);
}

void InitDefaultsSnapshotRequestImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    protobuf_metapb_2eproto::InitDefaultsRegion();
    protobuf_enginepb_2eproto::InitDefaultsSnapshotData();
    {
        void * ptr = &::enginepb::_SnapshotRequest_default_instance_;
        new (ptr)::enginepb::SnapshotRequest();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::SnapshotRequest::InitAsDefaultInstance();
}

void InitDefaultsSnapshotRequest()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSnapshotRequestImpl);
}

void InitDefaultsSnapshotDoneImpl()
{
    GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
    ::google::protobuf::internal::InitProtobufDefaults();
#endif // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
    {
        void * ptr = &::enginepb::_SnapshotDone_default_instance_;
        new (ptr)::enginepb::SnapshotDone();
        ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
    }
    ::enginepb::SnapshotDone::InitAsDefaultInstance();
}

void InitDefaultsSnapshotDone()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSnapshotDoneImpl);
}

::google::protobuf::Metadata file_level_metadata[7];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequetHeader, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequetHeader, region_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequetHeader, sync_log_),
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequet, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequet, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequet, requests_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequet, admin_request_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandRequet, admin_response_),
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::ResponseHeader, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::ResponseHeader, region_id_),
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandResponse, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandResponse, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::CommandResponse, apply_state_),
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotData, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotData, cf_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotData, checksum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotData, data_),
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotRequest, _internal_metadata_),
    ~0u, // no _extensions_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotRequest, _oneof_case_[0]),
    ~0u, // no _weak_field_map_
    offsetof(::enginepb::SnapshotRequestDefaultTypeInternal, region_),
    offsetof(::enginepb::SnapshotRequestDefaultTypeInternal, data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotRequest, chunk_),
    ~0u, // no _has_bits_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::enginepb::SnapshotDone, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    {0, -1, sizeof(::enginepb::CommandRequetHeader)},
    {7, -1, sizeof(::enginepb::CommandRequet)},
    {16, -1, sizeof(::enginepb::ResponseHeader)},
    {22, -1, sizeof(::enginepb::CommandResponse)},
    {29, -1, sizeof(::enginepb::SnapshotData)},
    {37, -1, sizeof(::enginepb::SnapshotRequest)},
    {45, -1, sizeof(::enginepb::SnapshotDone)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_CommandRequetHeader_default_instance_),
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_CommandRequet_default_instance_),
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_ResponseHeader_default_instance_),
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_CommandResponse_default_instance_),
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_SnapshotData_default_instance_),
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_SnapshotRequest_default_instance_),
    reinterpret_cast<const ::google::protobuf::Message *>(&::enginepb::_SnapshotDone_default_instance_),
};

void protobuf_AssignDescriptors()
{
    AddDescriptors();
    ::google::protobuf::MessageFactory * factory = NULL;
    AssignDescriptors("enginepb.proto", schemas, file_default_instances, TableStruct::offsets, factory, file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string &) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string &)
{
    protobuf_AssignDescriptorsOnce();
    ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 7);
}

void AddDescriptorsImpl()
{
    InitDefaults();
    static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold)
        = {"\n\016enginepb.proto\022\010enginepb\032\014metapb.proto"
           "\032\020raft_cmdpb.proto\032\023raft_serverpb.proto\""
           ":\n\023CommandRequetHeader\022\021\n\tregion_id\030\001 \001("
           "\004\022\020\n\010sync_log\030\002 \001(\010\"\311\001\n\rCommandRequet\022-\n"
           "\006header\030\001 \001(\0132\035.enginepb.CommandRequetHe"
           "ader\022%\n\010requests\030\002 \003(\0132\023.raft_cmdpb.Requ"
           "est\022/\n\radmin_request\030\003 \001(\0132\030.raft_cmdpb."
           "AdminRequest\0221\n\016admin_response\030\004 \001(\0132\031.r"
           "aft_cmdpb.AdminResponse\"#\n\016ResponseHeade"
           "r\022\021\n\tregion_id\030\001 \001(\004\"o\n\017CommandResponse\022"
           "(\n\006header\030\001 \001(\0132\030.enginepb.ResponseHeade"
           "r\0222\n\013apply_state\030\002 \001(\0132\035.raft_serverpb.R"
           "aftApplyState\"S\n\014SnapshotData\022\n\n\002cf\030\001 \001("
           "\t\022\020\n\010checksum\030\002 \001(\r\022%\n\004data\030\003 \003(\0132\027.raft"
           "_serverpb.KeyValue\"d\n\017SnapshotRequest\022 \n"
           "\006region\030\001 \001(\0132\016.metapb.RegionH\000\022&\n\004data\030"
           "\002 \001(\0132\026.enginepb.SnapshotDataH\000B\007\n\005chunk"
           "\"\016\n\014SnapshotDone2\232\001\n\006Engine\022H\n\014ApplyComm"
           "and\022\027.enginepb.CommandRequet\032\031.enginepb."
           "CommandResponse\"\000(\0010\001\022F\n\rApplySnapshot\022\031"
           ".enginepb.SnapshotRequest\032\026.enginepb.Sna"
           "pshotDone\"\000(\001b\006proto3"};
    ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(descriptor, 861);
    ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile("enginepb.proto", &protobuf_RegisterTypes);
    ::protobuf_metapb_2eproto::AddDescriptors();
    ::protobuf_raft_5fcmdpb_2eproto::AddDescriptors();
    ::protobuf_raft_5fserverpb_2eproto::AddDescriptors();
}

void AddDescriptors()
{
    static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
    ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer
{
    StaticDescriptorInitializer() { AddDescriptors(); }
} static_descriptor_initializer;
} // namespace protobuf_enginepb_2eproto
namespace enginepb
{

// ===================================================================

void CommandRequetHeader::InitAsDefaultInstance() {}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandRequetHeader::kRegionIdFieldNumber;
const int CommandRequetHeader::kSyncLogFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandRequetHeader::CommandRequetHeader() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsCommandRequetHeader();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.CommandRequetHeader)
}
CommandRequetHeader::CommandRequetHeader(const CommandRequetHeader & from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::memcpy(&region_id_,
             &from.region_id_,
             static_cast<size_t>(reinterpret_cast<char *>(&sync_log_) - reinterpret_cast<char *>(&region_id_)) + sizeof(sync_log_));
    // @@protoc_insertion_point(copy_constructor:enginepb.CommandRequetHeader)
}

void CommandRequetHeader::SharedCtor()
{
    ::memset(&region_id_,
             0,
             static_cast<size_t>(reinterpret_cast<char *>(&sync_log_) - reinterpret_cast<char *>(&region_id_)) + sizeof(sync_log_));
    _cached_size_ = 0;
}

CommandRequetHeader::~CommandRequetHeader()
{
    // @@protoc_insertion_point(destructor:enginepb.CommandRequetHeader)
    SharedDtor();
}

void CommandRequetHeader::SharedDtor() {}

void CommandRequetHeader::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * CommandRequetHeader::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CommandRequetHeader & CommandRequetHeader::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsCommandRequetHeader();
    return *internal_default_instance();
}

CommandRequetHeader * CommandRequetHeader::New(::google::protobuf::Arena * arena) const
{
    CommandRequetHeader * n = new CommandRequetHeader;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void CommandRequetHeader::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.CommandRequetHeader)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    ::memset(&region_id_,
             0,
             static_cast<size_t>(reinterpret_cast<char *>(&sync_log_) - reinterpret_cast<char *>(&region_id_)) + sizeof(sync_log_));
    _internal_metadata_.Clear();
}

bool CommandRequetHeader::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.CommandRequetHeader)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag))
        {
        // uint64 region_id = 1;
        case 1:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(8u /* 8 & 0xFF */))
            {

                DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<::google::protobuf::uint64,
                                                                                 ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                    input, &region_id_)));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // bool sync_log = 2;
        case 2:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(16u /* 16 & 0xFF */))
            {

                DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<bool,
                                                                                 ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                    input, &sync_log_)));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        default:
        {
        handle_unusual:
            if (tag == 0)
            {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
            break;
        }
        }
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.CommandRequetHeader)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.CommandRequetHeader)
    return false;
#undef DO_
}

void CommandRequetHeader::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.CommandRequetHeader)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // uint64 region_id = 1;
    if (this->region_id() != 0)
    {
        ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->region_id(), output);
    }

    // bool sync_log = 2;
    if (this->sync_log() != 0)
    {
        ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->sync_log(), output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.CommandRequetHeader)
}

::google::protobuf::uint8 * CommandRequetHeader::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                         ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.CommandRequetHeader)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // uint64 region_id = 1;
    if (this->region_id() != 0)
    {
        target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->region_id(), target);
    }

    // bool sync_log = 2;
    if (this->sync_log() != 0)
    {
        target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->sync_log(), target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.CommandRequetHeader)
    return target;
}

size_t CommandRequetHeader::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.CommandRequetHeader)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    // uint64 region_id = 1;
    if (this->region_id() != 0)
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::UInt64Size(this->region_id());
    }

    // bool sync_log = 2;
    if (this->sync_log() != 0)
    {
        total_size += 1 + 1;
    }

    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void CommandRequetHeader::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.CommandRequetHeader)
    GOOGLE_DCHECK_NE(&from, this);
    const CommandRequetHeader * source = ::google::protobuf::internal::DynamicCastToGenerated<const CommandRequetHeader>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.CommandRequetHeader)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.CommandRequetHeader)
        MergeFrom(*source);
    }
}

void CommandRequetHeader::MergeFrom(const CommandRequetHeader & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.CommandRequetHeader)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    if (from.region_id() != 0)
    {
        set_region_id(from.region_id());
    }
    if (from.sync_log() != 0)
    {
        set_sync_log(from.sync_log());
    }
}

void CommandRequetHeader::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.CommandRequetHeader)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void CommandRequetHeader::CopyFrom(const CommandRequetHeader & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.CommandRequetHeader)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool CommandRequetHeader::IsInitialized() const
{
    return true;
}

void CommandRequetHeader::Swap(CommandRequetHeader * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void CommandRequetHeader::InternalSwap(CommandRequetHeader * other)
{
    using std::swap;
    swap(region_id_, other->region_id_);
    swap(sync_log_, other->sync_log_);
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandRequetHeader::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CommandRequet::InitAsDefaultInstance()
{
    ::enginepb::_CommandRequet_default_instance_._instance.get_mutable()->header_
        = const_cast<::enginepb::CommandRequetHeader *>(::enginepb::CommandRequetHeader::internal_default_instance());
    ::enginepb::_CommandRequet_default_instance_._instance.get_mutable()->admin_request_
        = const_cast<::raft_cmdpb::AdminRequest *>(::raft_cmdpb::AdminRequest::internal_default_instance());
    ::enginepb::_CommandRequet_default_instance_._instance.get_mutable()->admin_response_
        = const_cast<::raft_cmdpb::AdminResponse *>(::raft_cmdpb::AdminResponse::internal_default_instance());
}
void CommandRequet::clear_requests()
{
    requests_.Clear();
}
void CommandRequet::clear_admin_request()
{
    if (GetArenaNoVirtual() == NULL && admin_request_ != NULL)
    {
        delete admin_request_;
    }
    admin_request_ = NULL;
}
void CommandRequet::clear_admin_response()
{
    if (GetArenaNoVirtual() == NULL && admin_response_ != NULL)
    {
        delete admin_response_;
    }
    admin_response_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandRequet::kHeaderFieldNumber;
const int CommandRequet::kRequestsFieldNumber;
const int CommandRequet::kAdminRequestFieldNumber;
const int CommandRequet::kAdminResponseFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandRequet::CommandRequet() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsCommandRequet();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.CommandRequet)
}
CommandRequet::CommandRequet(const CommandRequet & from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL), requests_(from.requests_), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    if (from.has_header())
    {
        header_ = new ::enginepb::CommandRequetHeader(*from.header_);
    }
    else
    {
        header_ = NULL;
    }
    if (from.has_admin_request())
    {
        admin_request_ = new ::raft_cmdpb::AdminRequest(*from.admin_request_);
    }
    else
    {
        admin_request_ = NULL;
    }
    if (from.has_admin_response())
    {
        admin_response_ = new ::raft_cmdpb::AdminResponse(*from.admin_response_);
    }
    else
    {
        admin_response_ = NULL;
    }
    // @@protoc_insertion_point(copy_constructor:enginepb.CommandRequet)
}

void CommandRequet::SharedCtor()
{
    ::memset(&header_,
             0,
             static_cast<size_t>(reinterpret_cast<char *>(&admin_response_) - reinterpret_cast<char *>(&header_))
                 + sizeof(admin_response_));
    _cached_size_ = 0;
}

CommandRequet::~CommandRequet()
{
    // @@protoc_insertion_point(destructor:enginepb.CommandRequet)
    SharedDtor();
}

void CommandRequet::SharedDtor()
{
    if (this != internal_default_instance())
        delete header_;
    if (this != internal_default_instance())
        delete admin_request_;
    if (this != internal_default_instance())
        delete admin_response_;
}

void CommandRequet::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * CommandRequet::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CommandRequet & CommandRequet::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsCommandRequet();
    return *internal_default_instance();
}

CommandRequet * CommandRequet::New(::google::protobuf::Arena * arena) const
{
    CommandRequet * n = new CommandRequet;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void CommandRequet::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.CommandRequet)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    requests_.Clear();
    if (GetArenaNoVirtual() == NULL && header_ != NULL)
    {
        delete header_;
    }
    header_ = NULL;
    if (GetArenaNoVirtual() == NULL && admin_request_ != NULL)
    {
        delete admin_request_;
    }
    admin_request_ = NULL;
    if (GetArenaNoVirtual() == NULL && admin_response_ != NULL)
    {
        delete admin_response_;
    }
    admin_response_ = NULL;
    _internal_metadata_.Clear();
}

bool CommandRequet::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.CommandRequet)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag))
        {
        // .enginepb.CommandRequetHeader header = 1;
        case 1:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(10u /* 10 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_header()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // repeated .raft_cmdpb.Request requests = 2;
        case 2:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(18u /* 18 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_requests()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // .raft_cmdpb.AdminRequest admin_request = 3;
        case 3:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(26u /* 26 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_admin_request()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // .raft_cmdpb.AdminResponse admin_response = 4;
        case 4:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(34u /* 34 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_admin_response()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        default:
        {
        handle_unusual:
            if (tag == 0)
            {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
            break;
        }
        }
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.CommandRequet)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.CommandRequet)
    return false;
#undef DO_
}

void CommandRequet::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.CommandRequet)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // .enginepb.CommandRequetHeader header = 1;
    if (this->has_header())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(1, *this->header_, output);
    }

    // repeated .raft_cmdpb.Request requests = 2;
    for (unsigned int i = 0, n = static_cast<unsigned int>(this->requests_size()); i < n; i++)
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(2, this->requests(static_cast<int>(i)), output);
    }

    // .raft_cmdpb.AdminRequest admin_request = 3;
    if (this->has_admin_request())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(3, *this->admin_request_, output);
    }

    // .raft_cmdpb.AdminResponse admin_response = 4;
    if (this->has_admin_response())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(4, *this->admin_response_, output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.CommandRequet)
}

::google::protobuf::uint8 * CommandRequet::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                   ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.CommandRequet)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // .enginepb.CommandRequetHeader header = 1;
    if (this->has_header())
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(1, *this->header_, deterministic, target);
    }

    // repeated .raft_cmdpb.Request requests = 2;
    for (unsigned int i = 0, n = static_cast<unsigned int>(this->requests_size()); i < n; i++)
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(
            2, this->requests(static_cast<int>(i)), deterministic, target);
    }

    // .raft_cmdpb.AdminRequest admin_request = 3;
    if (this->has_admin_request())
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(3, *this->admin_request_, deterministic, target);
    }

    // .raft_cmdpb.AdminResponse admin_response = 4;
    if (this->has_admin_response())
    {
        target
            = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(4, *this->admin_response_, deterministic, target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.CommandRequet)
    return target;
}

size_t CommandRequet::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.CommandRequet)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    // repeated .raft_cmdpb.Request requests = 2;
    {
        unsigned int count = static_cast<unsigned int>(this->requests_size());
        total_size += 1UL * count;
        for (unsigned int i = 0; i < count; i++)
        {
            total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(this->requests(static_cast<int>(i)));
        }
    }

    // .enginepb.CommandRequetHeader header = 1;
    if (this->has_header())
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this->header_);
    }

    // .raft_cmdpb.AdminRequest admin_request = 3;
    if (this->has_admin_request())
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this->admin_request_);
    }

    // .raft_cmdpb.AdminResponse admin_response = 4;
    if (this->has_admin_response())
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this->admin_response_);
    }

    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void CommandRequet::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.CommandRequet)
    GOOGLE_DCHECK_NE(&from, this);
    const CommandRequet * source = ::google::protobuf::internal::DynamicCastToGenerated<const CommandRequet>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.CommandRequet)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.CommandRequet)
        MergeFrom(*source);
    }
}

void CommandRequet::MergeFrom(const CommandRequet & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.CommandRequet)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    requests_.MergeFrom(from.requests_);
    if (from.has_header())
    {
        mutable_header()->::enginepb::CommandRequetHeader::MergeFrom(from.header());
    }
    if (from.has_admin_request())
    {
        mutable_admin_request()->::raft_cmdpb::AdminRequest::MergeFrom(from.admin_request());
    }
    if (from.has_admin_response())
    {
        mutable_admin_response()->::raft_cmdpb::AdminResponse::MergeFrom(from.admin_response());
    }
}

void CommandRequet::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.CommandRequet)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void CommandRequet::CopyFrom(const CommandRequet & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.CommandRequet)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool CommandRequet::IsInitialized() const
{
    return true;
}

void CommandRequet::Swap(CommandRequet * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void CommandRequet::InternalSwap(CommandRequet * other)
{
    using std::swap;
    requests_.InternalSwap(&other->requests_);
    swap(header_, other->header_);
    swap(admin_request_, other->admin_request_);
    swap(admin_response_, other->admin_response_);
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandRequet::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResponseHeader::InitAsDefaultInstance() {}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponseHeader::kRegionIdFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponseHeader::ResponseHeader() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsResponseHeader();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.ResponseHeader)
}
ResponseHeader::ResponseHeader(const ResponseHeader & from) : ::google::protobuf::Message(), _internal_metadata_(NULL), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    region_id_ = from.region_id_;
    // @@protoc_insertion_point(copy_constructor:enginepb.ResponseHeader)
}

void ResponseHeader::SharedCtor()
{
    region_id_    = GOOGLE_ULONGLONG(0);
    _cached_size_ = 0;
}

ResponseHeader::~ResponseHeader()
{
    // @@protoc_insertion_point(destructor:enginepb.ResponseHeader)
    SharedDtor();
}

void ResponseHeader::SharedDtor() {}

void ResponseHeader::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * ResponseHeader::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResponseHeader & ResponseHeader::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsResponseHeader();
    return *internal_default_instance();
}

ResponseHeader * ResponseHeader::New(::google::protobuf::Arena * arena) const
{
    ResponseHeader * n = new ResponseHeader;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void ResponseHeader::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.ResponseHeader)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    region_id_ = GOOGLE_ULONGLONG(0);
    _internal_metadata_.Clear();
}

bool ResponseHeader::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.ResponseHeader)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag))
        {
        // uint64 region_id = 1;
        case 1:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(8u /* 8 & 0xFF */))
            {

                DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<::google::protobuf::uint64,
                                                                                 ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                    input, &region_id_)));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        default:
        {
        handle_unusual:
            if (tag == 0)
            {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
            break;
        }
        }
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.ResponseHeader)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.ResponseHeader)
    return false;
#undef DO_
}

void ResponseHeader::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.ResponseHeader)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // uint64 region_id = 1;
    if (this->region_id() != 0)
    {
        ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->region_id(), output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.ResponseHeader)
}

::google::protobuf::uint8 * ResponseHeader::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                    ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.ResponseHeader)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // uint64 region_id = 1;
    if (this->region_id() != 0)
    {
        target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->region_id(), target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.ResponseHeader)
    return target;
}

size_t ResponseHeader::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.ResponseHeader)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    // uint64 region_id = 1;
    if (this->region_id() != 0)
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::UInt64Size(this->region_id());
    }

    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void ResponseHeader::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.ResponseHeader)
    GOOGLE_DCHECK_NE(&from, this);
    const ResponseHeader * source = ::google::protobuf::internal::DynamicCastToGenerated<const ResponseHeader>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.ResponseHeader)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.ResponseHeader)
        MergeFrom(*source);
    }
}

void ResponseHeader::MergeFrom(const ResponseHeader & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.ResponseHeader)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    if (from.region_id() != 0)
    {
        set_region_id(from.region_id());
    }
}

void ResponseHeader::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.ResponseHeader)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void ResponseHeader::CopyFrom(const ResponseHeader & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.ResponseHeader)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool ResponseHeader::IsInitialized() const
{
    return true;
}

void ResponseHeader::Swap(ResponseHeader * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void ResponseHeader::InternalSwap(ResponseHeader * other)
{
    using std::swap;
    swap(region_id_, other->region_id_);
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ResponseHeader::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CommandResponse::InitAsDefaultInstance()
{
    ::enginepb::_CommandResponse_default_instance_._instance.get_mutable()->header_
        = const_cast<::enginepb::ResponseHeader *>(::enginepb::ResponseHeader::internal_default_instance());
    ::enginepb::_CommandResponse_default_instance_._instance.get_mutable()->apply_state_
        = const_cast<::raft_serverpb::RaftApplyState *>(::raft_serverpb::RaftApplyState::internal_default_instance());
}
void CommandResponse::clear_apply_state()
{
    if (GetArenaNoVirtual() == NULL && apply_state_ != NULL)
    {
        delete apply_state_;
    }
    apply_state_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandResponse::kHeaderFieldNumber;
const int CommandResponse::kApplyStateFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandResponse::CommandResponse() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsCommandResponse();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.CommandResponse)
}
CommandResponse::CommandResponse(const CommandResponse & from) : ::google::protobuf::Message(), _internal_metadata_(NULL), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    if (from.has_header())
    {
        header_ = new ::enginepb::ResponseHeader(*from.header_);
    }
    else
    {
        header_ = NULL;
    }
    if (from.has_apply_state())
    {
        apply_state_ = new ::raft_serverpb::RaftApplyState(*from.apply_state_);
    }
    else
    {
        apply_state_ = NULL;
    }
    // @@protoc_insertion_point(copy_constructor:enginepb.CommandResponse)
}

void CommandResponse::SharedCtor()
{
    ::memset(&header_,
             0,
             static_cast<size_t>(reinterpret_cast<char *>(&apply_state_) - reinterpret_cast<char *>(&header_)) + sizeof(apply_state_));
    _cached_size_ = 0;
}

CommandResponse::~CommandResponse()
{
    // @@protoc_insertion_point(destructor:enginepb.CommandResponse)
    SharedDtor();
}

void CommandResponse::SharedDtor()
{
    if (this != internal_default_instance())
        delete header_;
    if (this != internal_default_instance())
        delete apply_state_;
}

void CommandResponse::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * CommandResponse::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CommandResponse & CommandResponse::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsCommandResponse();
    return *internal_default_instance();
}

CommandResponse * CommandResponse::New(::google::protobuf::Arena * arena) const
{
    CommandResponse * n = new CommandResponse;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void CommandResponse::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.CommandResponse)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    if (GetArenaNoVirtual() == NULL && header_ != NULL)
    {
        delete header_;
    }
    header_ = NULL;
    if (GetArenaNoVirtual() == NULL && apply_state_ != NULL)
    {
        delete apply_state_;
    }
    apply_state_ = NULL;
    _internal_metadata_.Clear();
}

bool CommandResponse::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.CommandResponse)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag))
        {
        // .enginepb.ResponseHeader header = 1;
        case 1:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(10u /* 10 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_header()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // .raft_serverpb.RaftApplyState apply_state = 2;
        case 2:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(18u /* 18 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_apply_state()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        default:
        {
        handle_unusual:
            if (tag == 0)
            {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
            break;
        }
        }
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.CommandResponse)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.CommandResponse)
    return false;
#undef DO_
}

void CommandResponse::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.CommandResponse)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // .enginepb.ResponseHeader header = 1;
    if (this->has_header())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(1, *this->header_, output);
    }

    // .raft_serverpb.RaftApplyState apply_state = 2;
    if (this->has_apply_state())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(2, *this->apply_state_, output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.CommandResponse)
}

::google::protobuf::uint8 * CommandResponse::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                     ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.CommandResponse)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // .enginepb.ResponseHeader header = 1;
    if (this->has_header())
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(1, *this->header_, deterministic, target);
    }

    // .raft_serverpb.RaftApplyState apply_state = 2;
    if (this->has_apply_state())
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(2, *this->apply_state_, deterministic, target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.CommandResponse)
    return target;
}

size_t CommandResponse::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.CommandResponse)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    // .enginepb.ResponseHeader header = 1;
    if (this->has_header())
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this->header_);
    }

    // .raft_serverpb.RaftApplyState apply_state = 2;
    if (this->has_apply_state())
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*this->apply_state_);
    }

    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void CommandResponse::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.CommandResponse)
    GOOGLE_DCHECK_NE(&from, this);
    const CommandResponse * source = ::google::protobuf::internal::DynamicCastToGenerated<const CommandResponse>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.CommandResponse)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.CommandResponse)
        MergeFrom(*source);
    }
}

void CommandResponse::MergeFrom(const CommandResponse & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.CommandResponse)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    if (from.has_header())
    {
        mutable_header()->::enginepb::ResponseHeader::MergeFrom(from.header());
    }
    if (from.has_apply_state())
    {
        mutable_apply_state()->::raft_serverpb::RaftApplyState::MergeFrom(from.apply_state());
    }
}

void CommandResponse::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.CommandResponse)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void CommandResponse::CopyFrom(const CommandResponse & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.CommandResponse)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool CommandResponse::IsInitialized() const
{
    return true;
}

void CommandResponse::Swap(CommandResponse * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void CommandResponse::InternalSwap(CommandResponse * other)
{
    using std::swap;
    swap(header_, other->header_);
    swap(apply_state_, other->apply_state_);
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandResponse::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SnapshotData::InitAsDefaultInstance() {}
void SnapshotData::clear_data()
{
    data_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SnapshotData::kCfFieldNumber;
const int SnapshotData::kChecksumFieldNumber;
const int SnapshotData::kDataFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

SnapshotData::SnapshotData() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsSnapshotData();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.SnapshotData)
}
SnapshotData::SnapshotData(const SnapshotData & from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL), data_(from.data_), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    cf_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    if (from.cf().size() > 0)
    {
        cf_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cf_);
    }
    checksum_ = from.checksum_;
    // @@protoc_insertion_point(copy_constructor:enginepb.SnapshotData)
}

void SnapshotData::SharedCtor()
{
    cf_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    checksum_     = 0u;
    _cached_size_ = 0;
}

SnapshotData::~SnapshotData()
{
    // @@protoc_insertion_point(destructor:enginepb.SnapshotData)
    SharedDtor();
}

void SnapshotData::SharedDtor()
{
    cf_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SnapshotData::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * SnapshotData::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SnapshotData & SnapshotData::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsSnapshotData();
    return *internal_default_instance();
}

SnapshotData * SnapshotData::New(::google::protobuf::Arena * arena) const
{
    SnapshotData * n = new SnapshotData;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void SnapshotData::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.SnapshotData)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    data_.Clear();
    cf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    checksum_ = 0u;
    _internal_metadata_.Clear();
}

bool SnapshotData::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.SnapshotData)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag))
        {
        // string cf = 1;
        case 1:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(10u /* 10 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadString(input, this->mutable_cf()));
                DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(this->cf().data(),
                                                                                   static_cast<int>(this->cf().length()),
                                                                                   ::google::protobuf::internal::WireFormatLite::PARSE,
                                                                                   "enginepb.SnapshotData.cf"));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // uint32 checksum = 2;
        case 2:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(16u /* 16 & 0xFF */))
            {

                DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<::google::protobuf::uint32,
                                                                                 ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                    input, &checksum_)));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // repeated .raft_serverpb.KeyValue data = 3;
        case 3:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(26u /* 26 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_data()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        default:
        {
        handle_unusual:
            if (tag == 0)
            {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
            break;
        }
        }
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.SnapshotData)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.SnapshotData)
    return false;
#undef DO_
}

void SnapshotData::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.SnapshotData)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // string cf = 1;
    if (this->cf().size() > 0)
    {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(this->cf().data(),
                                                                       static_cast<int>(this->cf().length()),
                                                                       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                                                                       "enginepb.SnapshotData.cf");
        ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(1, this->cf(), output);
    }

    // uint32 checksum = 2;
    if (this->checksum() != 0)
    {
        ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->checksum(), output);
    }

    // repeated .raft_serverpb.KeyValue data = 3;
    for (unsigned int i = 0, n = static_cast<unsigned int>(this->data_size()); i < n; i++)
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(3, this->data(static_cast<int>(i)), output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.SnapshotData)
}

::google::protobuf::uint8 * SnapshotData::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                  ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.SnapshotData)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // string cf = 1;
    if (this->cf().size() > 0)
    {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(this->cf().data(),
                                                                       static_cast<int>(this->cf().length()),
                                                                       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
                                                                       "enginepb.SnapshotData.cf");
        target = ::google::protobuf::internal::WireFormatLite::WriteStringToArray(1, this->cf(), target);
    }

    // uint32 checksum = 2;
    if (this->checksum() != 0)
    {
        target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->checksum(), target);
    }

    // repeated .raft_serverpb.KeyValue data = 3;
    for (unsigned int i = 0, n = static_cast<unsigned int>(this->data_size()); i < n; i++)
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(
            3, this->data(static_cast<int>(i)), deterministic, target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.SnapshotData)
    return target;
}

size_t SnapshotData::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.SnapshotData)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    // repeated .raft_serverpb.KeyValue data = 3;
    {
        unsigned int count = static_cast<unsigned int>(this->data_size());
        total_size += 1UL * count;
        for (unsigned int i = 0; i < count; i++)
        {
            total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(this->data(static_cast<int>(i)));
        }
    }

    // string cf = 1;
    if (this->cf().size() > 0)
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(this->cf());
    }

    // uint32 checksum = 2;
    if (this->checksum() != 0)
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::UInt32Size(this->checksum());
    }

    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void SnapshotData::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.SnapshotData)
    GOOGLE_DCHECK_NE(&from, this);
    const SnapshotData * source = ::google::protobuf::internal::DynamicCastToGenerated<const SnapshotData>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.SnapshotData)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.SnapshotData)
        MergeFrom(*source);
    }
}

void SnapshotData::MergeFrom(const SnapshotData & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.SnapshotData)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    data_.MergeFrom(from.data_);
    if (from.cf().size() > 0)
    {

        cf_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cf_);
    }
    if (from.checksum() != 0)
    {
        set_checksum(from.checksum());
    }
}

void SnapshotData::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.SnapshotData)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void SnapshotData::CopyFrom(const SnapshotData & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.SnapshotData)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool SnapshotData::IsInitialized() const
{
    return true;
}

void SnapshotData::Swap(SnapshotData * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void SnapshotData::InternalSwap(SnapshotData * other)
{
    using std::swap;
    data_.InternalSwap(&other->data_);
    cf_.Swap(&other->cf_);
    swap(checksum_, other->checksum_);
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SnapshotData::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SnapshotRequest::InitAsDefaultInstance()
{
    ::enginepb::_SnapshotRequest_default_instance_.region_ = const_cast<::metapb::Region *>(::metapb::Region::internal_default_instance());
    ::enginepb::_SnapshotRequest_default_instance_.data_
        = const_cast<::enginepb::SnapshotData *>(::enginepb::SnapshotData::internal_default_instance());
}
void SnapshotRequest::set_allocated_region(::metapb::Region * region)
{
    ::google::protobuf::Arena * message_arena = GetArenaNoVirtual();
    clear_chunk();
    if (region)
    {
        ::google::protobuf::Arena * submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            region = ::google::protobuf::internal::GetOwnedMessage(message_arena, region, submessage_arena);
        }
        set_has_region();
        chunk_.region_ = region;
    }
    // @@protoc_insertion_point(field_set_allocated:enginepb.SnapshotRequest.region)
}
void SnapshotRequest::clear_region()
{
    if (has_region())
    {
        delete chunk_.region_;
        clear_has_chunk();
    }
}
void SnapshotRequest::set_allocated_data(::enginepb::SnapshotData * data)
{
    ::google::protobuf::Arena * message_arena = GetArenaNoVirtual();
    clear_chunk();
    if (data)
    {
        ::google::protobuf::Arena * submessage_arena = NULL;
        if (message_arena != submessage_arena)
        {
            data = ::google::protobuf::internal::GetOwnedMessage(message_arena, data, submessage_arena);
        }
        set_has_data();
        chunk_.data_ = data;
    }
    // @@protoc_insertion_point(field_set_allocated:enginepb.SnapshotRequest.data)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SnapshotRequest::kRegionFieldNumber;
const int SnapshotRequest::kDataFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

SnapshotRequest::SnapshotRequest() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsSnapshotRequest();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.SnapshotRequest)
}
SnapshotRequest::SnapshotRequest(const SnapshotRequest & from) : ::google::protobuf::Message(), _internal_metadata_(NULL), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    clear_has_chunk();
    switch (from.chunk_case())
    {
    case kRegion:
    {
        mutable_region()->::metapb::Region::MergeFrom(from.region());
        break;
    }
    case kData:
    {
        mutable_data()->::enginepb::SnapshotData::MergeFrom(from.data());
        break;
    }
    case CHUNK_NOT_SET:
    {
        break;
    }
    }
    // @@protoc_insertion_point(copy_constructor:enginepb.SnapshotRequest)
}

void SnapshotRequest::SharedCtor()
{
    clear_has_chunk();
    _cached_size_ = 0;
}

SnapshotRequest::~SnapshotRequest()
{
    // @@protoc_insertion_point(destructor:enginepb.SnapshotRequest)
    SharedDtor();
}

void SnapshotRequest::SharedDtor()
{
    if (has_chunk())
    {
        clear_chunk();
    }
}

void SnapshotRequest::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * SnapshotRequest::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SnapshotRequest & SnapshotRequest::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsSnapshotRequest();
    return *internal_default_instance();
}

SnapshotRequest * SnapshotRequest::New(::google::protobuf::Arena * arena) const
{
    SnapshotRequest * n = new SnapshotRequest;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void SnapshotRequest::clear_chunk()
{
    // @@protoc_insertion_point(one_of_clear_start:enginepb.SnapshotRequest)
    switch (chunk_case())
    {
    case kRegion:
    {
        delete chunk_.region_;
        break;
    }
    case kData:
    {
        delete chunk_.data_;
        break;
    }
    case CHUNK_NOT_SET:
    {
        break;
    }
    }
    _oneof_case_[0] = CHUNK_NOT_SET;
}


void SnapshotRequest::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.SnapshotRequest)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    clear_chunk();
    _internal_metadata_.Clear();
}

bool SnapshotRequest::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.SnapshotRequest)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
        switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag))
        {
        // .metapb.Region region = 1;
        case 1:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(10u /* 10 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_region()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        // .enginepb.SnapshotData data = 2;
        case 2:
        {
            if (static_cast<::google::protobuf::uint8>(tag) == static_cast<::google::protobuf::uint8>(18u /* 18 & 0xFF */))
            {
                DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_data()));
            }
            else
            {
                goto handle_unusual;
            }
            break;
        }

        default:
        {
        handle_unusual:
            if (tag == 0)
            {
                goto success;
            }
            DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
            break;
        }
        }
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.SnapshotRequest)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.SnapshotRequest)
    return false;
#undef DO_
}

void SnapshotRequest::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.SnapshotRequest)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // .metapb.Region region = 1;
    if (has_region())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(1, *chunk_.region_, output);
    }

    // .enginepb.SnapshotData data = 2;
    if (has_data())
    {
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(2, *chunk_.data_, output);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.SnapshotRequest)
}

::google::protobuf::uint8 * SnapshotRequest::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                     ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.SnapshotRequest)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    // .metapb.Region region = 1;
    if (has_region())
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(1, *chunk_.region_, deterministic, target);
    }

    // .enginepb.SnapshotData data = 2;
    if (has_data())
    {
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(2, *chunk_.data_, deterministic, target);
    }

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.SnapshotRequest)
    return target;
}

size_t SnapshotRequest::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.SnapshotRequest)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    switch (chunk_case())
    {
    // .metapb.Region region = 1;
    case kRegion:
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*chunk_.region_);
        break;
    }
    // .enginepb.SnapshotData data = 2;
    case kData:
    {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*chunk_.data_);
        break;
    }
    case CHUNK_NOT_SET:
    {
        break;
    }
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void SnapshotRequest::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.SnapshotRequest)
    GOOGLE_DCHECK_NE(&from, this);
    const SnapshotRequest * source = ::google::protobuf::internal::DynamicCastToGenerated<const SnapshotRequest>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.SnapshotRequest)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.SnapshotRequest)
        MergeFrom(*source);
    }
}

void SnapshotRequest::MergeFrom(const SnapshotRequest & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.SnapshotRequest)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    switch (from.chunk_case())
    {
    case kRegion:
    {
        mutable_region()->::metapb::Region::MergeFrom(from.region());
        break;
    }
    case kData:
    {
        mutable_data()->::enginepb::SnapshotData::MergeFrom(from.data());
        break;
    }
    case CHUNK_NOT_SET:
    {
        break;
    }
    }
}

void SnapshotRequest::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.SnapshotRequest)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void SnapshotRequest::CopyFrom(const SnapshotRequest & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.SnapshotRequest)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool SnapshotRequest::IsInitialized() const
{
    return true;
}

void SnapshotRequest::Swap(SnapshotRequest * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void SnapshotRequest::InternalSwap(SnapshotRequest * other)
{
    using std::swap;
    swap(chunk_, other->chunk_);
    swap(_oneof_case_[0], other->_oneof_case_[0]);
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SnapshotRequest::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SnapshotDone::InitAsDefaultInstance() {}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

SnapshotDone::SnapshotDone() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
    if (GOOGLE_PREDICT_TRUE(this != internal_default_instance()))
    {
        ::protobuf_enginepb_2eproto::InitDefaultsSnapshotDone();
    }
    SharedCtor();
    // @@protoc_insertion_point(constructor:enginepb.SnapshotDone)
}
SnapshotDone::SnapshotDone(const SnapshotDone & from) : ::google::protobuf::Message(), _internal_metadata_(NULL), _cached_size_(0)
{
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    // @@protoc_insertion_point(copy_constructor:enginepb.SnapshotDone)
}

void SnapshotDone::SharedCtor()
{
    _cached_size_ = 0;
}

SnapshotDone::~SnapshotDone()
{
    // @@protoc_insertion_point(destructor:enginepb.SnapshotDone)
    SharedDtor();
}

void SnapshotDone::SharedDtor() {}

void SnapshotDone::SetCachedSize(int size) const
{
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor * SnapshotDone::descriptor()
{
    ::protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SnapshotDone & SnapshotDone::default_instance()
{
    ::protobuf_enginepb_2eproto::InitDefaultsSnapshotDone();
    return *internal_default_instance();
}

SnapshotDone * SnapshotDone::New(::google::protobuf::Arena * arena) const
{
    SnapshotDone * n = new SnapshotDone;
    if (arena != NULL)
    {
        arena->Own(n);
    }
    return n;
}

void SnapshotDone::Clear()
{
    // @@protoc_insertion_point(message_clear_start:enginepb.SnapshotDone)
    ::google::protobuf::uint32 cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _internal_metadata_.Clear();
}

bool SnapshotDone::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream * input)
{
#define DO_(EXPRESSION)                   \
    if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) \
    goto failure
    ::google::protobuf::uint32 tag;
    // @@protoc_insertion_point(parse_start:enginepb.SnapshotDone)
    for (;;)
    {
        ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
        tag                                             = p.first;
        if (!p.second)
            goto handle_unusual;
    handle_unusual:
        if (tag == 0)
        {
            goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(input, tag, _internal_metadata_.mutable_unknown_fields()));
    }
success:
    // @@protoc_insertion_point(parse_success:enginepb.SnapshotDone)
    return true;
failure:
    // @@protoc_insertion_point(parse_failure:enginepb.SnapshotDone)
    return false;
#undef DO_
}

void SnapshotDone::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream * output) const
{
    // @@protoc_insertion_point(serialize_start:enginepb.SnapshotDone)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        ::google::protobuf::internal::WireFormat::SerializeUnknownFields((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                                                                              ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
                                                                         output);
    }
    // @@protoc_insertion_point(serialize_end:enginepb.SnapshotDone)
}

::google::protobuf::uint8 * SnapshotDone::InternalSerializeWithCachedSizesToArray(bool                        deterministic,
                                                                                  ::google::protobuf::uint8 * target) const
{
    (void)deterministic; // Unused
    // @@protoc_insertion_point(serialize_to_array_start:enginepb.SnapshotDone)
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()),
            target);
    }
    // @@protoc_insertion_point(serialize_to_array_end:enginepb.SnapshotDone)
    return target;
}

size_t SnapshotDone::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:enginepb.SnapshotDone)
    size_t total_size = 0;

    if ((_internal_metadata_.have_unknown_fields() && ::google::protobuf::internal::GetProto3PreserveUnknownsDefault()))
    {
        total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault() ? _internal_metadata_.unknown_fields()
                                                                              : _internal_metadata_.default_instance()));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cached_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    return total_size;
}

void SnapshotDone::MergeFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_merge_from_start:enginepb.SnapshotDone)
    GOOGLE_DCHECK_NE(&from, this);
    const SnapshotDone * source = ::google::protobuf::internal::DynamicCastToGenerated<const SnapshotDone>(&from);
    if (source == NULL)
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_fail:enginepb.SnapshotDone)
        ::google::protobuf::internal::ReflectionOps::Merge(from, this);
    }
    else
    {
        // @@protoc_insertion_point(generalized_merge_from_cast_success:enginepb.SnapshotDone)
        MergeFrom(*source);
    }
}

void SnapshotDone::MergeFrom(const SnapshotDone & from)
{
    // @@protoc_insertion_point(class_specific_merge_from_start:enginepb.SnapshotDone)
    GOOGLE_DCHECK_NE(&from, this);
    _internal_metadata_.MergeFrom(from._internal_metadata_);
    ::google::protobuf::uint32 cached_has_bits = 0;
    (void)cached_has_bits;
}

void SnapshotDone::CopyFrom(const ::google::protobuf::Message & from)
{
    // @@protoc_insertion_point(generalized_copy_from_start:enginepb.SnapshotDone)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

void SnapshotDone::CopyFrom(const SnapshotDone & from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:enginepb.SnapshotDone)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool SnapshotDone::IsInitialized() const
{
    return true;
}

void SnapshotDone::Swap(SnapshotDone * other)
{
    if (other == this)
        return;
    InternalSwap(other);
}
void SnapshotDone::InternalSwap(SnapshotDone * other)
{
    using std::swap;
    _internal_metadata_.Swap(&other->_internal_metadata_);
    swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SnapshotDone::GetMetadata() const
{
    protobuf_enginepb_2eproto::protobuf_AssignDescriptorsOnce();
    return ::protobuf_enginepb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
} // namespace enginepb

// @@protoc_insertion_point(global_scope)
