// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kvrpcpb.proto
#ifndef GRPC_kvrpcpb_2eproto__INCLUDED
#define GRPC_kvrpcpb_2eproto__INCLUDED

#include "kvrpcpb.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace kvrpcpb {

}  // namespace kvrpcpb


#endif  // GRPC_kvrpcpb_2eproto__INCLUDED
